apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-celeryworker
  labels:
    component: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: celeryworker
  template:
    metadata:
      labels:
        component: celeryworker
    spec:
      containers:
        - name: celeryworker
          image: bogdanp3trovic/shigoto_q_production_celeryworker
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: sharedpv
              mountPath: /app
              readOnly: true
          args:
            - /start-celeryworker
          env:
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: django-configmap
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: django-configmap
            - name: DOCKER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_SERVICE_URL
                  name: django-configmap
            - name: GKE_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  key: GKE_CLUSTER_NAME
                  name: django-configmap
            - name: GKE_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: GKE_PROJECT_NAME
                  name: django-configmap
            - name: GKE_SERVICE_ACCOUNT_NAME
              valueFrom:
                configMapKeyRef:
                  key: GKE_SERVICE_ACCOUNT_NAME
                  name: django-configmap
            - name: GKE_ZONE
              valueFrom:
                configMapKeyRef:
                  key: GKE_ZONE
                  name: django-configmap
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_APPLICATION_CREDENTIALS
                  name: django-configmap
            - name: IPYTHONDIR
              valueFrom:
                configMapKeyRef:
                  key: IPYTHONDIR
                  name: django-configmap
            - name: LIVE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: LIVE_SECRET_KEY
                  name: django-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: django-configmap
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_DSN
                  name: django-configmap
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_ENVIRONMENT
                  name: django-configmap
            - name: TEST_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: TEST_SECRET_KEY
                  name: django-configmap
            - name: USE_DOCKER
              valueFrom:
                configMapKeyRef:
                  key: USE_DOCKER
                  name: django-configmap
            - name: WEBHOOK_SECRET
              valueFrom:
                configMapKeyRef:
                  key: WEBHOOK_SECRET
                  name: django-configmap
      volumes:
      - name: sharedpv
        persistentVolumeClaim:
          claimName: shared-pv
        
